name: chocolatine

on:
  push:
    branches-ignore:
      - 'ga-ignore-*'
  pull_request:

env:
  MIRROR_URL: <epitech_mirror_url>
  EXECUTABLES: "pushswap, lib/my/libmy.a"

jobs:
  check_coding_style:
    runs-on: ubuntu-latest
    container: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Check coding style
        run: check.sh $(pwd) $(pwd)
      - name: Report coding style errors
        if: ${{ failure() }}
        uses: peter-evans/create-or-update-comment@v1.3.1
        with:
          issue-number: ${{ github.event.number }}
          body: |
            ## :warning: Coding style errors detected :warning:

            The following coding style errors were detected in your code:

            ```
            ${{ env.CODING_STYLE_ERRORS }}
            ```
          reactions: "+1"

  check_program_compilation:
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    timeout-minutes: 2
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build program
        run: make
      - name: Clean build artifacts
        run: make clean
      - name: Verify executables
        run: |
          for exe in $EXECUTABLES; do
            if [ ! -x "$exe" ]; then
              echo "$exe is not executable or does not exist"
              exit 1
            fi
          done

  run_tests:
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    timeout-minutes: 2
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run tests
        run: make tests_run

  push_to_mirror:
    runs-on: ubuntu-latest
    needs: [check_program_compilation, run_tests]
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Mirror repository
        uses: pixta-dev/repository-mirroring-action@v1.0.0
        with:
          ssh-private-key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
          src-repository: ${{ github.repository }}
          dest-repository: ${{ env.MIRROR_URL }}
