name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
env:
  EXECUTABLES: yo
  MIRROR_URL: ya
jobs:
  check_coding_style:
    runs-on: ubuntu-latest
    container: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - name: Check coding style
        uses: actions/checkout@v3
      - run: |
          check.sh $(pwd) $(pwd)
          if [ -s $coding-style-reports.log ]
          then
            exit 0
          else
            while read line
            do
               tab=(${line//:/ })
               ya=(${tab[0]})
               tob=(${ya//// })
               echo "::error title=${tab[2]} coding style error: ${tob[1]}#L${tab[1]}::${tab[3]}"
            done < coding-style-reports.log
            exit 1
          fi
  check_program_compilation:
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    steps:
      - name: check compilation
        uses: actions/checkout@v3
      - run: |
          make
          make clean
          ls > oyoy
          while read line
          do
            if [ "$line" = "$EXECUTABLES" ]
            then
              exit 0
            fi
          done < oyoy
          exit 1
