on:
  push:
    branches-ignore:
      - 'ga-ignore-**'
  workflow_dispatch:
  pull_request:
env:
  EXECUTABLES:  ""
  MIRROR_URL:  ""

jobs:
  check_the_coding_style:
    runs-on:  ubuntu-latest
    container:
      image: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - uses:  actions/checkout@v3
      - run:  |
          check.sh $(pwd) $(pwd)
          cat coding-style-reports.log
          input="coding-style-reports.log"
          g=0
          while IFS= read -r line
          do
            g+=1
            readarray -d ' ' -t tab<<<"$line"
            readarray -d ':' -t ol<<<"${tab[1]}"
            readarray -d ':' -t oli<<<"${tab[0]}"
            echo "::error file=${oli[0]},title=${ol[0]} coding style error,line=${oli[1]}::${ol[1]}"
          done < "$input"
          if [ $g -ne 0 ]
          then
            exit 1
          fi
  check_program_compilation:
    needs:  check_the_coding_style
    runs-on:  ubuntu-latest
    container:
      image:  epitechcontent/epitest-docker:latest
    steps:
      - uses:  actions/checkout@v3
      - run: ls -l
      - run:  make
      - run:  make clean
      - run:  |
          if ! test -fx ${EXECUTABLES}
          then
            exit 1
          fi
  run_tests:
    needs:  check_program_compilation
    runs-on:  ubuntu-latest
    container:
      image:  epitechcontent/epitest-docker:latest
    steps:
      - uses: actions/checkout@v3
      - run:  |
          echo "tests_run:" >> Makefile
      - run:  make tests_run
  push_to_mirror:
    runs-on:  ubuntu-latest
    needs:  run_tests
    steps:
      - uses: actions/checkout@v3
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:  ${MIRROR_URL}
          ssh-private-key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
