name: CI

on:
  push:
    branches-ignore:
      - 'ga-ignore-'
  pull_request:
    branches-ignore:
      - 'ga-ignore-'

jobs:
  check_repository_cleanliness:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Unwanted file detected
        run: |
          TEST=$(find *)
          echo $TEST if startsWith($TEST, '#') && endsWith($TEST, '#') || endsWith($TEST, '~') || contains(github.event.issue.labels.*.name, 'pain_au_chocolat' || endsWith($TEST, '.o') ||
          endsWith($TEST, '.a') ||
          endsWith($TEST, '.so') ||
          endsWith($TEST, '.gcno') ||
          endsWith($TEST, '.gcda') ||
          startsWith($TEST, 'tmp/')
