name: Display repository size

on: [ push ]

jobs:
  get-repository-size:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "${{github.branch.head_ref}}"
          du -skh --exclude=".git"
