name: Display repository size

on: [ push ]

jobs:
  get-repository-size:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "${{ github.ref }}"
      - run: du -skh --exclude=".git"
